/* 按层获取课件组列表 */
export const GET_COURSEWARES = "GET_COURSEWARES";
export const GET_COURSEWARES_SUCCESS = "GET_COURSEWARES_SUCCESS";
export const GET_COURSEWARES_FAILURE = "GET_COURSEWARES_SUCCESS_FAILURE";
/* 课件组列表v3版 */
export const GET_COURSEWARES_GROUP = "GET_COURSEWARES_GROUP";
export const GET_COURSEWARES_GROUP_SUCCESS = "GET_COURSEWARES_GROUP_SUCCESS";
export const GET_COURSEWARES_GROUP_FAILURE = "GET_COURSEWARES_GROUP_FAILURE";
/* get.subFile */
export const GET_SUBFILE = "GET_SUBFILE";
export const GET_SUBFILE_SUCCESS = "GET_SUBFILE_SUCCESS";
// export const GET_COURSEWARES_GROUP_FAILURE = "GET_COURSEWARES_SUCCESS_FAILURE";
/* 生成分享链接 */
export const CREATE_G_SHARELINK = "CREATE_G_SHARELINK";
export const CREATE_G_SHARELINK_SUCCESS = "CREATE_G_SHARELINK_SUCCESS";
export const CREATE_G_SHARELINK_FAILURE = "CREATE_G_SHARELINK_FAILURE";
/* 获取所有层级课件组 */
export const GET_ALL_GROUP = "GET_ALL_GROUP";
export const GET_ALL_GROUP_SUCCESS = "GET_ALL_GROUP_SUCCESS";
export const GET_ALL_GROUP_FAILURE = "GET_ALL_GROUP_FAILURE";
/* 移动课件 */
export const MOVE_HERE = "MOVE_HERE";
export const MOVE_HERE_SUCCESS = "MOVE_HERE_SUCCESS";
export const MOVE_HERE_FAILURE = "MOVE_HERE_FAILURE";
/* 新建课件组 */
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_SUCCESS = "CREATE_FOLDER_SUCCESS";
export const CREATE_FOLDER_FAILURE = "CREATE_FOLDER_FAILURE";
/* 获取课件历史 */
export const GET_HISTORY = "GET_HISTORY";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILURE = "GET_HISTORY_FAILURE";
/* 获取简要文档信息 */
export const GET_INFO = "GET_INFO";
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_FAILURE = "GET_INFO_FAILURE";
/* 控制面包屑 */
export const GET_BREAD = "GET_BREAD";
export const GET_BREAD_SUCCESS = "GET_BREAD_SUCCESS";
export const GET_BREAD_FAILURE = "GET_BREAD_FAILURE";
/* 刷新数据 */
export const REFRESH = 'REFRESH' 
    export const REFRESH_SUCCESS ='REFRESH_SUCCESS'
    export const REFRESH_FAILURE = 'REFRESH_FAILURE'