/* 按层获取课件组列表 */
export const GET_COURSEWARES = "GET_COURSEWARES";
export const GET_COURSEWARES_SUCCESS = "GET_COURSEWARES_SUCCESS";
export const GET_COURSEWARES_FAILURE = "GET_COURSEWARES_SUCCESS_FAILURE";
/* 课件组列表v3版 */
export const GET_COURSEWARES_GROUP = "GET_COURSEWARES";
export const GET_COURSEWARES_GROUP_SUCCESS = "GET_COURSEWARES_SUCCESS";
export const GET_COURSEWARES_GROUP_FAILURE = "GET_COURSEWARES_SUCCESS_FAILURE";
